### ISSUE TITLE
[BUG] Kubuntu Tray Icon

### ISSUE THREAD

**Issue by Valdes-Tresanco-MS** [liberodark/ODrive#100]
The tray icon is not displayed on the Kubuntu desktop. I use Ubuntu 18.04.2. The Kubuntu desktop was installed from the ubuntu repository
![image](https://user-images.githubusercontent.com/36672242/57115148-c268d580-6d12-11e9-821d-5ab1c218ab63.png)

**Comment by liberodark** [comment]
Sorry but that is work on official version :D have test you use unofficial version.

**Comment by liberodark** [comment]
Please open a bug Request

**Comment by liberodark** [comment]
You need tu use official version / https://github.com/liberodark/ODrive/releases/download/0.2.2/odrive_0.2.2_amd64.deb
