### ISSUE TITLE
[Feature Request] Choose source folder

### ISSUE THREAD

**Issue by BedoM** [liberodark/ODrive#105]
Hey !

Can you add the feature to Choose the source folder on my google drive ?

thank's

ps: sorry for my English i'm french :)

**Comment by BedoM** [comment]
#30 ? It is in work in progress ?

**Comment by liberodark** [comment]
Bonjour,

Je vous rassure c'est prévu donc cela fait un peu doublon si c'est la meme demande.

Cordialement
