### ISSUE TITLE
Packaging error

### ISSUE THREAD

**Issue by liberodark** [liberodark/ODrive#11]
Currently we can no longer compile the project.

electron-packager . --overwrite --platform=linux --arch=x64 --prune=true --out=release-builds
Packaging app for platform linux x64 using electron v1.7.6
Command failed: npm prune --production
npm WARN bootstrap@4.0.0-beta requires a peer of popper.js@^1.11.0 but none was installed.
npm WARN sass-loader@6.0.6 requires a peer of node-sass@^4.0.0 but none was installed.
npm WARN sass-loader@6.0.6 requires a peer of webpack@^2.0.0 || >= 3.0.0-rc.0 || ^3.0.0 but none was installed.

npm ERR! May not delete: /tmp/electron-packager/linux-x64/odrive-linux-x64/resources/app/node_modules/.bin

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pc/.npm/_logs/2017-09-09T17_56_56_807Z-debug.log

**Comment by coyotte508** [comment]
Weird. When everything's done, it may be worth looking into another packager.

**Comment by coyotte508** [comment]
Try this:  `sudo npm install -g npm@5.2.0`

npm 5.3.0 seems to have problems: https://github.com/npm/npm/issues/17858
