### ISSUE TITLE
Odrive not starting up on Ubuntu 18.04

### ISSUE THREAD

**Issue by jomajojo** [liberodark/ODrive#120]
Odrive after a fresh install of Kubuntu 18.04 doesn't launch on startup. 

here is a piece of my snap list
Name               Version          Rev   Tracking  Publisher   Notes
---------
odrive             latest           67    edge      bill-666    -

Once started manually, odrive is working fine.
regards

**Comment by liberodark** [comment]
yes use deb v0.2.2
