### ISSUE TITLE
Icon Offline Status

### ISSUE THREAD

**Issue by liberodark** [liberodark/ODrive#14]
Hello,

Icon don't when where offline.

Cordialy

**Comment by coyotte508** [comment]
Can you confirm this still happens with the latest version?

Also can you post logs (after 2 minutes of being offline).

**Comment by liberodark** [comment]
Is not work tray icon dont change in offline after 2min

**Comment by liberodark** [comment]
Terminal : 

npm start

> odrive@0.1.1 start /home/pc/Bureau/odrive/ODrive-master
> electron main

/home/pc/Bureau/odrive/ODrive-master/public
app started on port 16409
Updating account info
Local files registered:  4
Watching remote changes...
Initial scan complete. Ready for changes
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443 }
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,

**Comment by coyotte508** [comment]
Fixed in https://github.com/liberodark/ODrive/commit/df761d6181e753c599072dc655b397683944bc4e

**Comment by liberodark** [comment]
Terminal : 

npm start

> odrive@0.1.1 start /home/pc/Bureau/odrive/ODrive-master
> electron main

/home/pc/Bureau/odrive/ODrive-master/public
app started on port 16409
Updating account info
Local files registered:  4
Watching remote changes...
Initial scan complete. Ready for changes
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Updated connection status
Unhandled rejection Error processing argument at index 0, conversion failure from public/logo-grey.png
TypeError: Error processing argument at index 0, conversion failure from public/logo-grey.png
    at updateTrayIcon (/home/pc/Bureau/odrive/ODrive-master/main.js:91:12)
    at Globals.gbs.on (/home/pc/Bureau/odrive/ODrive-master/main.js:85:5)
    at emitOne (events.js:96:13)
    at Globals.emit (events.js:191:7)
    at Globals.updateConnectivity (/home/pc/Bureau/odrive/ODrive-master/config/globals.js:23:10)
    at process.on (/home/pc/Bureau/odrive/ODrive-master/app/backend.js:66:13)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:194:7)
    at emitPendingUnhandledRejections (internal/process/promises.js:85:22)
    at runMicrotasksCallback (internal/process/next_tick.js:67:9)
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }
Watching remote changes...
Error when watching changes...
Unhandled rejection getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
Connection error when watching changes, restarting in 10 seconds
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443,
  watcher: true }

**Comment by coyotte508** [comment]
The first "Updated connection status" should have done the job.

Can you give me your system's specifications so I can run a VM and check?
