### ISSUE TITLE
[BUG] ODrive not starting

### ISSUE THREAD

**Issue by miguel9554** [liberodark/ODrive#141]
**Describe the bug**
I downloaded the AppImage, but when I run it the console outputs the following, but the GUI does not start

```
[miguel@localhost bin]$ ./OpenDrive.0.2.1.AppImage 
/tmp/.mount_OpenDrTdKxyG/resources/app.asar/public
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
app started on port 16409
remote change false false
local change false false
Updating account info
Updating tray icon, connected:  true syncing:  false
Initial scan complete. Ready for changes
Saving account to db
Saved account!
```

**To Reproduce**
I do not know the exact conditions as I downloaded and runed the AppImage previously, but I don't know what kind of config files (if any) it spreads over the filesystem.

**Desktop (please complete the following information):**
 - OS: Fedora 30
 - Version: 0.2.2

**Additional context**
I had downloaded in the past ODrive, but because of an issue similar to [this](https://github.com/liberodark/ODrive/issues/135) I removed it and then I downloaded it again.

**Comment by liberodark** [comment]
Try to see this : https://github.com/liberodark/ODrive/issues/67

**Comment by miguel9554** [comment]
I solved it installing through snap, previously I was downloading the AppImage directly from https://github.com/liberodark/ODrive/releases
