### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by PhoneixS** [liberodark/ODrive#150]
**Is your feature request related to a problem? Please describe.**
Google Drive has the pictures of Google Photos in a folder called "Google Fotos" which is pretty big and I don't really want to synchronize. So is there a way to ignore a folder?

**Describe the solution you'd like**
It would be very nice to have a list of directories to ignore the synchronization. Something simple like you should write the full folder path one per line and it skipped it if it matches.

**Comment by liberodark** [comment]
Duplicated https://github.com/liberodark/ODrive/issues/28

**Comment by PhoneixS** [comment]
I don't think it's a duplicate of #28, my case is the opposite.

I want to ignore files/folders that that are synchronized so they don't synchronize. On the other hand, the other issue already has ignored files (Google docs) that want to get synchronized.
