### ISSUE TITLE
[BUG] TypeError: files is not iterable

### ISSUE THREAD

**Issue by lugodu34** [liberodark/ODrive#152]
Hi,

When I try to configure the folder to synchronize, I get : 
```
TypeError: files is not iterable
    at Sync.downloadFolderStructure (/home/hugo/Téléchargements/ODrive/app/core/sync.js:755:22)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Sync.start (/home/hugo/Téléchargements/ODrive/app/core/sync.js:195:19)
    at async IpcMain.<anonymous> (/home/hugo/Téléchargements/ODrive/app/routes/settings.js:84:5)
```
The steps I follow:
1. Go to the ODrive folder
2. run "npm install"
3. run "npm start"
4. In the GUI window, connect your GDrive account : ok.
5. Choose the folder to synchronize.
6. Click on "synchronize"
7. See the error "Files is not iterable"

Have I missed a step? Is anyone knows what to do to fix it?

 - OS: Ubuntu 19.10 64 bits
 - ODrive 0.3.0
- Node.js v10.15.2
- npm 5.8.0

Thanks!

**Comment by mattgebert** [comment]
I have the same bug. 
### Code:
`TypeError: files is not iterable`
    `    at Sync.downloadFolderStructure (/opt/odrive/app/core/sync.js:755:22)`
    `    at async Sync.start (/opt/odrive/app/core/sync.js:195:19)`
    `    at async IpcMainImpl.<anonymous> (/opt/odrive/app/routes/settings.js:84:5)`

**Comment by lugodu34** [comment]
I installed it using a .deb package and it works!

Le jeu. 13 févr. 2020 à 06:23, Matt Gebert <notifications@github.com> a
écrit :

**Comment by mimavox** [comment]
Same error on Mac :(
Any updates about this? As it is now, I cannot even begin to use the software..

**Comment by lczech** [comment]
Same here, using the setup as described [here](https://github.com/liberodark/ODrive). Then, I saw the comment above about using a `.deb` file instead, and got the [latest release](https://github.com/liberodark/ODrive/releases), which seems to work. 

Let's hope it stays this way! I have tried `n` different clients for syncing Google Drive now, and hope that ODrive is the one that finally works...
