### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by mmppeegg** [liberodark/ODrive#153]
I can install this app and do npm start. The UI first requests me to log in Google account, but after I key in my account, "Couldn't sign you in" dialog shows.
Is there any way can solve this?

**Comment by gabdara** [comment]
I have the same issue.
Any fix or workaround for this?

**Comment by cserpell** [comment]
I have used odrive for months, and now my account stopped working, when tried to sign in again, the same message appears: "Couldn't sign you in". It says the browser or app may not be secure. For the record, I have two factor authentication on. The complete message:

Couldn't sign you in

This browser or app may not be secure. Learn more

Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

**Comment by billy1380** [comment]
There is a workaround here https://github.com/liberodark/ODrive/issues/147 which will allow you to use your browser. Just go to 127.0.0.1:16409/settings... It is not all good news though... google now says: Sign in with Google temporarily disabled for this app so you still cannot log in :(

**Comment by cserpell** [comment]
> There is a workaround here #147 which will allow you to use your browser. Just go to 127.0.0.1:16409/settings... It is not all good news though... google now says: Sign in with Google temporarily disabled for this app so you still cannot log in :(

So this is a duplicate issue, good to know. This bug then should be closed.

**Comment by liberodark** [comment]
Duplicated
