### ISSUE TITLE
Create DEB / RPM Packages

### ISSUE THREAD

**Issue by liberodark** [liberodark/ODrive#18]
Hello,

This thread for help to make deb & rpm pakage.
for red hat / debian.

for deb : https://github.com/unindented/electron-installer-debian
for rpm : https://github.com/unindented/electron-installer-redhat

Cordialy

**Comment by liberodark** [comment]
RPM Error :  
http://pastobin.altervista.org/paste.php?id=8

**Comment by MaikoID** [comment]
I will levare here the deps that I had to install:

npm install tether sass-loader popper.js  nedb-promise morgan  mkdirp-promise  jquery  font-awesome  file-loader  ejs  bootstrap body-parser array-unique  command-line-args chokidar electron  node-notifier

**Comment by liberodark** [comment]
Yes but im try to find a solution for compress app in DEB / RPM is other problem

**Comment by coyotte508** [comment]
```bash
npm run release-linux deb
npm run release-linux rpm
```
:)
