### ISSUE TITLE
Dependencies Updates !

### ISSUE THREAD

**Issue by liberodark** [liberodark/ODrive#19]
Have new updates of dependencies !

**Most Important :** 

electron              ^1.6.6  →   ^1.7.8
googleapis                   ^19.0.0  →  ^22.2.0 
eslint                       ^3.19.0  →   ^4.8.0 
file-loader                  ^0.11.1  →   ^1.1.4 
 md5-file              ^3.1.1  →   ^3.2.3 

**Others :** 

 fs-extra                      ^3.0.1  →   ^4.0.2 
 extract-text-webpack-plugin   ^2.1.0  →   ^3.0.1 
 style-loader                 ^0.17.0  →  ^0.19.0 
 url-loader                    ^0.5.8  →   ^0.6.2 
 webpack                       ^2.5.1  →   ^3.6.0 
 body-parser          ^1.17.1  →  ^1.18.2 
 chokidar              ^1.6.1  →   ^1.7.0 
 command-line-args     ^4.0.4  →   ^4.0.7 
 ejs                   ^2.5.6  →   ^2.5.7 
 express              ^4.15.2  →  ^4.16.1 
 morgan                ^1.8.1  →   ^1.9.0 
 sass-loader           ^6.0.3  →   ^6.0.6 
 copy-webpack-plugin   ^4.0.1  →   ^4.1.0 
 css-loader           ^0.28.1  →  ^0.28.7 
 node-sass             ^4.5.2  →   ^4.5.3 
 resolve-url-loader    ^2.0.2  →   ^2.1.0

**Comment by coyotte508** [comment]
Don't break the repo without testing? At least do it not in the master branch?

**Comment by liberodark** [comment]
Have new update for fix that is coming
