### ISSUE TITLE
Error after run "sudo npm install -g electron webpack eslint"

### ISSUE THREAD

**Issue by weyderfs** [liberodark/ODrive#20]
Hello, I'm has problem to install, after run the command cited on subject terminal return this following error:

`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm ERR! Linux 4.8.0-59-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-sass@4.7.2 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@4.7.2 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kerberosti/ODrive/npm-debug.log`

[npm-debug.log](https://github.com/liberodark/ODrive/files/1556289/npm-debug.log)

Do you have idea how to solve this? hahaha

**Comment by coyotte508** [comment]
Try this:

```bash
sudo npm install -g n
sudo n stable
```
Or this:

```
sudo ln -s `which nodejs` /usr/bin/node
```

The first option will also update your nodejs, the second is a lot less intrusive. The reason for the error is because of this: https://stackoverflow.com/questions/18130164/nodejs-vs-node-on-ubuntu-12-04

**Comment by Automatik** [comment]
I got a error at the same command, so I post it here, but it's a different error from the previous.

**Terminal Output:**
`/usr/local/bin/electron -> /usr/local/lib/node_modules/electron/cli.js
/usr/local/bin/eslint -> /usr/local/lib/node_modules/eslint/bin/eslint.js
/usr/local/bin/webpack -> /usr/local/lib/node_modules/webpack/bin/webpack.js

> electron@1.7.10 postinstall /usr/local/lib/node_modules/electron
> node install.js

/usr/local/lib/node_modules/electron/install.js:48
  throw err
  ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/electron/.electron'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/webpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.10 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.7.10 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/emil/.npm/_logs/2017-12-19T11_49_36_154Z-debug.log
`



I tried changing the permission of npm's subfolders with 
`sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}`
but nothing. Got the same error.
I saw there is an issue opened on electron's github at this [link](https://github.com/electron/electron/issues/9323)

Any idea how to solve this?

**Comment by coyotte508** [comment]
The first thing would be to update node / npm:

```
sudo npm install -g n
sudo n stable
```

Also, which command exactly is causing the error? `sudo npm install -g electron webpack eslint` or `npm install` ?

**Comment by coyotte508** [comment]
https://github.com/electron-userland/electron-prebuilt/issues/263

```
sudo npm install -g electron --unsafe-perm=true --allow-root
```

I will edit the Readme.

**Comment by coyotte508** [comment]
I removed the need for the command altogether in https://github.com/liberodark/ODrive/commit/91b02502e49c2a75879728b46314f8f6fb475203

I also updated the README to add this step instead: `sudo apt install libgconf-2-4` (needed for the newer version of electron).

Please tell me if it works :)

**Comment by Automatik** [comment]
Yes, it worked thank you.
So for the _Setup_ a little recap of what I did:

First executed `sudo npm install -g electron webpack eslint` but I got errors.

So I executed `sudo npm install -g electron --unsafe-perm=true --allow-root` (it takes a little time, otherwise stop with Ctrl+Z, retry and should be fine)

Then I run: `sudo apt install libgconf-2-4` but it was already up to date (for the first npm install of electron)

And finally go to step _Build_
