### ISSUE TITLE
Synchronize button not working 

### ISSUE THREAD

**Issue by Automatik** [liberodark/ODrive#21]
I open a new issue beacuse a different problem.
After building the project i run `npm start`, the interface opens, I log in with my google account, select folder to which sync my files to and click synchronize button but nothing happen.

In the terminal:

> odrive@0.1.1 start /home/emil/ODrive
> electron main
`
`
/home/emil/ODrive/public
app started on port 16409
Updating account info
Updating tray icon, connected:  true
Initial scan complete. Ready for changes
Saving account to db
Saved account!
Get home page
Number of accounts 1
GET / 302 55.198 ms - 62
GET /settings 304 44.092 ms - -
GET /javascript/preload.js 404 18.260 ms - 160
GET /javascript/jquery.min.js 404 20.396 ms - 163
GET /javascript/tether.min.js 404 17.734 ms - 163
GET /stylesheets/styles.css 404 17.710 ms - 161
GET /javascript/frontend.js 404 21.730 ms - 161
GET /javascript/settings.js 404 21.363 ms - 161`

If I run `npm test` I get this:

> odrive@0.1.1 test /home/emil/ODrive
> npm run lint
`
`
> odrive@0.1.1 lint /home/emil/ODrive
> eslint app main.js
`
`
/home/emil/ODrive/app/assets/javascript/settings.js
  32:25  error  'sender' is defined but never used  no-unused-vars
  52:19  error  'sender' is defined but never used  no-unused-vars
`
:heavy_multiplication_x: 2 problems (2 errors, 0 warnings)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! odrive@0.1.1 lint: eslint app main.js
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the odrive@0.1.1 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! Test failed.  See above for more details.

Any idea also for this?

**Comment by coyotte508** [comment]
Ok, so what happened is that I changed the build script to remove the need for installing globally webpack, eslint and electron. I also changed the readme.

So your best bet would be to update your repository, and rerun npm install. It will call webpack to build the js / css files, and it will make the app look a lot better!

Alternatively, you can just call `webpack` in the project directory, and rerun the app.
