### ISSUE TITLE
Please provide an AppImage for download

### ISSUE THREAD

**Issue by probonopd** [liberodark/ODrive#22]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by liberodark** [comment]
Hello,

It's a very good idea !
I will see this to see if it is feasible.

cordially

**Comment by liberodark** [comment]
Have create pull request for add odrive on your hub
0.1.2 is comming for an AppImage

**Comment by coyotte508** [comment]
https://github.com/electron-userland/electron-builder

Electron-builder seems to provide the ability to create appimages, as well as other formats (deb packages, windows installer, native mac...), see example package.json: https://github.com/ginhton/m2-list/blob/1a95b7d6e6e6a76c666d32d89ac8d6b5ac4ebf95/package.json

Might be worth it to remove support for electron-packager and use electron-builder instead.

**Comment by probonopd** [comment]
> Electron-builder seems to provide the ability to create appimages

electron-packager can be made to build AppImages as well, see https://github.com/electron-userland/electron-packager/issues/428#issuecomment-292724143

**Comment by coyotte508** [comment]
I added electron-builder and removed electron-packager (no point to keep it, electron-builder can already do everything it does).

The AppImage is uploading, I have a slow internet here. Not sure I did a good job with setting the ODrive icon to the AppImage, I followed electron-builder's documentation for the icons...
