### ISSUE TITLE
Syncing indicator

### ISSUE THREAD

**Issue by giovannicaligaris** [liberodark/ODrive#25]
Would it be possible to show when ODrive is syncing? (linux)

Maybe a similar icon like Mega does.

![mega](https://user-images.githubusercontent.com/26255347/37928871-3ac9c846-3136-11e8-95b6-0d160b6e2b43.png)

**Comment by coyotte508** [comment]
Maybe, a good first step would be to have a syncing icon. I'm not a designer!

**Comment by giovannicaligaris** [comment]
I have created 3 icons in 16/24/32/48 pixels in svg's.

![odrive](https://user-images.githubusercontent.com/26255347/37983336-10685cb0-31eb-11e8-8d28-71b170445ff4.png) ![odrive-syncing](https://user-images.githubusercontent.com/26255347/37983370-329d9d54-31eb-11e8-90c2-0391e9934d9d.png) ![odrive-offline](https://user-images.githubusercontent.com/26255347/37983378-38a96142-31eb-11e8-866a-780698ee77d5.png)

Let me know what do you think so I can summit them.

**Comment by coyotte508** [comment]
The two logos already present are 1024x1024 pngs. I need at least a 256x256 one for the syncing. 

You can make a PR to add `logo-sync.png` (or .svg) to public/: https://github.com/liberodark/ODrive/tree/master/public

Maybe you can also add a separate image, `sync.png`, with just the wheel in it. Who knows, I *may* be able to work something out to overlay it on the logo dynamically and make it rotate (not at the beginning though).

**Comment by giovannicaligaris** [comment]
Alright, I will do that soon.

Don't you think is better to work with .svg rather than png?

I can turn logo.png and logo-grey.png into svg's if you like to.

**Comment by coyotte508** [comment]
Sure, but I don't know if electron will support them well across OS's as an icon.

**Comment by giovannicaligaris** [comment]
In that case I will do both png and svg.

**Comment by giovannicaligaris** [comment]
Got all the logos ready.

I'm going to apologize but I am not very git savvy, I am not really sure how to push the files into the public folder.

If you don't mind, here's a link a zip file I made 

https://1drv.ms/u/s!Ag3swdfzZLvHbq8RBn2H0i-SbGg

**Comment by giovannicaligaris** [comment]
@coyotte508 did you have a chance to take a look at the zip file?

**Comment by coyotte508** [comment]
The svg were not working as a tray icon for electron. Maybe there was a way to use them, but I didn't delve.

The syncing icon now displays. As a bonus, notifications of changes only display when all changes are done. (They are grouped better).

I notice I have really bad upload speed with ODrive (150 kB/s), I don't know if this is a widespread problem.

**Comment by giovannicaligaris** [comment]
I am having a similar issue with the upload speed but not everytime. Maybe is an issue with Google?

**Comment by coyotte508** [comment]
That or their nodejs driver :)

**Comment by coyotte508** [comment]
Oops, I just noticed I didn't push it on this repo. It's done, you can build from source.

**Comment by giovannicaligaris** [comment]
Just tested, works great. Speed is fine also.
