### ISSUE TITLE
Start on startup

### ISSUE THREAD

**Issue by giovannicaligaris** [liberodark/ODrive#26]
Under settings there should be an option that allows to "Start on startup" (linux)

**Comment by liberodark** [comment]
Yes is next features !

**Comment by coyotte508** [comment]
Done in https://github.com/liberodark/ODrive/commit/f2e6de0819141b667fcc473616a9e70a70b24238 , version `0.2.0`.

It's only available on bundled packages, as described in the readme. For example `npm run release-windows` on a functioning build (where `npm start` works) will generate an installer in the `dist` folder, which will have the auto launch functionality.

**Comment by coyotte508** [comment]
It's done. I'm also reopening the issue because the feature is not currently working on AppImage. Can you test it works fine with a deb file?

**Comment by giovannicaligaris** [comment]
The deb works fine. Good job!

**Comment by liberodark** [comment]
Thx for your try !
