### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by jasonleakey** [liberodark/ODrive#34]
Hi @liberodark,

I'd like to contribute to the project. I personally don't find good alternatives of Google Drive for linux, so I want to build one too using electron + nautilus integration + app indicator. Could you add me in? Or how can I contribute otherwise?

Thanks.

**Comment by liberodark** [comment]
Hi,

You need to create a fork !
If you have any idea or bug fix found commit this and pull request.

Cordialy

**Comment by jasonleakey** [comment]
Thanks. Will do!
