### ISSUE TITLE
System tray icon not showing in ubuntu communitheme

### ISSUE THREAD

**Issue by i4m-15h4n** [liberodark/ODrive#37]
In ubuntu 18.04 ,
I can not find the system tray icon when using communitheme (both in xorg & wayland)
But normally the icon is there if logged in without communitheme.

**Comment by iam-i5h4n** [comment]
I wrote the same issue at ubuntu's communitheme repo.
Please have a look at what the dev did say:
https://github.com/ubuntu/yaru/issues/731

**Comment by liberodark** [comment]
Thank you for the information I'm going to look at this if it comes from electron we will go to the new version so it'll take a little time but I'll do that quickly.

**Comment by dev01d** [comment]
Looks like this was merged into v3.0.0-beta.1 here https://github.com/electron/electron/pull/12362
