### ISSUE TITLE
Update files based on timestamp

### ISSUE THREAD

**Issue by fpunktz** [liberodark/ODrive#42]
My files get synchronized but apparently they are not checked for edits / new timestamps. Installed via the Ubuntu Software Center / Snap package

**Comment by gabdantas** [comment]
Same problem here with odrive version 0.2.0. 
Also installed via Ubuntu Software Center on my Xubuntu 64bit.

**Comment by liberodark** [comment]
ok try with appimage in 0.2.1 but explain me you edit word file and is not sync ?

**Comment by liberodark** [comment]
now have push official release sudo snap install --edge odrive
