### ISSUE TITLE
Systray icon not appearing in Kubuntu

### ISSUE THREAD

**Issue by mhmulati** [liberodark/ODrive#48]
Hello

The systray icon of OpenDrive is not being showed in Kubuntu 18.04. There is a space, that act as the icon when mouse right-button pressed.

Any ideas of what is going on?

Thank you
Best
Mauro Henrique

**Comment by giovannicaligaris** [comment]
You need to change the Exec= in order to work.

Open terminal and paste this

`nano ~/.local/share/applications/odrive.desktop`

```
[Desktop Entry]
Name=Open Drive
Comment=Simple google drive client
Exec=env XDG_CURRENT_DESKTOP=Unity odrive %U
Terminal=false
Type=Application
Icon=odrive
Categories=Network;
```

kill odrive and launch it again

`killall odrive`

**Comment by mhmulati** [comment]
Thank you, it worked! I change de command in the autostart entry. However, when the system starts, odrive appears with an yellow icon, but soon turns gray, and never became yellow again (and is not syncronizing), even if I turn the net on. Then, if a kill and start again the odrive, it works fine.

I realize this problem better now, by seeing the icons.

Any idea how to solve?

**Comment by giovannicaligaris** [comment]
You might need to delay the time it takes for ODrive to open at startup. On Gnome/Elementary OS this is a very simple fix. All you need to do is add X-GNOME-Autostart-Delay=10 on the .desktop file.

I am not sure what is the equivalent for KDE.

If you figure out, please let me know.

**Comment by mhmulati** [comment]
I have edited the file ~/.config/autostart/odrive.desktop to have the content (changed the Exec atribute):

[Desktop Entry]
Type=Application
Version=1.0
Name=odrive
Comment=odrivestartup script
Exec=sleep 33s && env XDG_CURRENT_DESKTOP=Unity /opt/OpenDrive/odrive %U &
StartupNotify=false
Terminal=false

It looks like a glitch, but, I have tried a couple of thing and they didn't work.

Cheers

**Comment by raribeiro** [comment]
Here the problem persists, even with the delay.

**Comment by liberodark** [comment]
Oh but is not official version other version have this error ?

**Comment by bohyunl** [comment]
I using odrive on debian sid xfce, fedora 29 gnome, kde neon 18.04 and arch linux kde.
this problem only appear on kde.
![odrive-kde](https://user-images.githubusercontent.com/48006450/55074659-3a206080-50d4-11e9-90fa-af1f137e2b97.png)

**Comment by liberodark** [comment]
Is work on kde neon 2019 : https://i.imgur.com/Ov3HnPj.png
