### ISSUE TITLE
ODrive Validity Check Error in Manjaro from AUR..!!

### ISSUE THREAD

**Issue by zerocoolroot** [liberodark/ODrive#49]
Sorry my bad english, I'm from Brazil..!!

I'm trying to install odrive in Manjaro from AUR.

I getting the following error:

Validating source files with **sha256sums**...
    **odrive-0-3.py ... FAIL**
    odriveagent.sh ... Passed
    odrive.service ... Passed
    odrive@.service ... Passed
ERROR: One or more files did not pass the validity check!

Any ideia..??

Thank you so much..!!

**Comment by liberodark** [comment]
hi sorry but aur have remove odrive-bin is  not odrive in aur
