### ISSUE TITLE
Where is the MacOS .dmg installer?

### ISSUE THREAD

**Issue by EricTheRed1** [liberodark/ODrive#55]
How in the world do you install ODrive on MacOS?  There is no .dmg to download and the terminal  build instructions do not work, as there is no apt command on MacOS.

**Comment by liberodark** [comment]
is not easy but PR is welcome

**Comment by liberodark** [comment]
have error when try to make dmg is not easy need help for that so sorry :(

**Comment by liberodark** [comment]
Fixed on 0.2.2 :D
