### ISSUE TITLE
Cannot reopen window

### ISSUE THREAD

**Issue by joshcangit** [liberodark/ODrive#62]
There is no way to reopen the window or show a tray icon to know if the synchronization is active.
I had to reinstall ODrive in order to synchronize the files again.
**ODrive version:** 
```
Name               Version  Rev  Tracking  Publisher   Notes
odrive-unofficial  0.2.0    2    stable    ishan-bn14  -
```
**Snap version:**
```
snap    2.37.1.1+18.04
snapd   2.37.1.1+18.04
series  16
ubuntu  18.04
```
**OS version:**
```
Description:	Ubuntu 18.04.1 LTS
```

**Comment by joshcangit** [comment]
I'm not sure if this can be solved since this issue is specific to my desktop environment.

**Comment by liberodark** [comment]
Why is you desktop ?

**Comment by liberodark** [comment]
now have push official release sudo snap install --edge odrive

**Comment by joshcangit** [comment]
It doesn't look like it has been fixed. Still unable to reopen the window without reinstalling ODrive.
