### ISSUE TITLE
Unable to sync files

### ISSUE THREAD

**Issue by joaov777** [liberodark/ODrive#63]
I've installed this piece of software on a manjaro machine via snap and appimage. Everything worked just fine and all files from the drive were properly downloaded. However, the sync seems to work only from the web interface towards the folder on my machine. Every time I put a file on the folder, it never gets updated on Google Drive (as I check on the web interface). 

I'd like to know if there is a way around this or even if it's just me not paying enough attention. So far, thanks for the awesome tool.

**Comment by joshcangit** [comment]
Usually it fails to sync to Google Drive that it would only sync from Google Drive.

**Comment by joaov777** [comment]
Thanks for your quick answer, @joshcangit 

I've been looking for a proper Google Drive client for Linux and it's been taking longer than I actually expected. This one so far has been the best in my opinion. However, **the option for synchronizing from the local folder is actually incredibly useful**. 

I have just installed a onedrive client that performs the sync both ways. Is there any branch under development currently or it is not on the plans to make it happen?

**Comment by joshcangit** [comment]
I'm pretty sure ODrive is just for Google Drive.
It seems to me that it synchronizes only from Google Drive rather than in both directions.
I have opened Issue #64 for this particular problem.

**Comment by joaov777** [comment]
Hello, @joshcangit 
Thanks for opening the issue. I believe this is super important. Since the onedrive package does it, I'm sure ODrive will soon be able to do it too.

**Comment by liberodark** [comment]
is good idea yes to add onedrive support !

**Comment by joaov777** [comment]
> is good idea yes to add onedrive support !

As I mentioned, onedrive already works both ways and I'd appreciate if ODrive could do the same. It'd be amazing. Thanks for your input anyway.

**Comment by liberodark** [comment]
https://github.com/liberodark/ODrive/issues/64 is same
