### ISSUE TITLE
Drive File Stream vs Backup and Sync "Need users suggestions"

### ISSUE THREAD

**Issue by liberodark** [liberodark/ODrive#69]
Hello,

The purpose of this issue and to know your wishes as users of ODrive!

I felt obliged once again to face google who now offers two types of offers.
- Backup and Sync (Personal)
- Drive File Stream (Professional)
And since 2018 I have not had time to see all this in 2018.
I know the difference between the two.
And I will present it to you:

- Backup and Sync (Personal)
This is the current mode of ODrive bidirectional synchronization.
Which stock on the pc and in the cloud.

- Drive File Stream (Professional)
It is a mode that is present in the chromebook it allows to have a big drive for example 100 GB in the drive and your pc has only 32 GB of storage.
One can speak of automatic / unidirectional syncronization.
Why because if you send a file for example mydoc.docx it will be stored automatically on the pc and the drive but in case of difficulty you can simply no longer store the file and keep it only in the drive.
To be even more precise Drive File Stream is a little more efficient because it will only temporarily store the files on the pc and it will be accessible directly from pc via the drive.

Well now the question:

- Should this feature be implemented in odrive?
- ODrive should be similar to (Backup and Sync)?
- ODrive should be similar to (Drive File Stream)?
- ODrive must stay as he is?
- ODrive must have both features?

Here I think I have gone around the subject of you to tell me.

Best Regards

**Comment by gonesimera** [comment]
I think that ODrive should be similar to (Backup and Sync) myself, but the stream sounds interesting.

It is an amazing application that you have created, thanks.

**Comment by Summerer** [comment]
> I think that ODrive should be similar to (Backup and Sync) myself, but the stream sounds interesting.
> 
> It is an amazing application that you have created, thanks.

I agree with @gonesimera that ODrive should be similar to Backup and Sync because I think that's what most people would expect from a Google Drive client.
In addition, the option to selectively **not** sync a large folder, for instance, might be useful to some Google Drive power users.

**Comment by The-Graphite-Mog** [comment]
I think it should be similar to Backup and Sync, too. Actually, I'm happy that I've found Google Client for Ubuntu. It's already a really good application and easy to use. A nice feature would be to be able to deselect certain files/folders on both sides.

**Comment by via-justa** [comment]
Agree with the previous comments, The main reason I chose to use your (awesome) project is the offline files as I use the computer on the road. I'll agree with @Summerer that selective sync will be a better implementation that can make your project really stand out when comparing to the rest of the options.

PS. 
Any plans to update SNAP with the latest version?

Continue with the good job!!

**Comment by liberodark** [comment]
snap is build auto in last version

**Comment by mikaelmello** [comment]
A similar mode to Drive File Stream is implemented by https://github.com/astrada/google-drive-ocamlfuse, I've been using it but I'd much rather use ODrive because of the offline mode. Files can take a large time to open or update

**Comment by liberodark** [comment]
thanks all for your reply !
