### ISSUE TITLE
impelement google doc link files

### ISSUE THREAD

**Issue by allenyllee** [liberodark/ODrive#70]
Hi, I've been using Google Drive for windows version many years, it creates link file for google docs. Now I want to move to your app, but it's missing the function to create google docs link file.

The content of link file is just a text file, for example:
```
{"url": "https://docs.google.com/open?id=1bYv-iWY-3Mh1Y8XdbbHJtXJLpvqLlu0pvkJOVib52IM", "doc_id": "1bYv-iWY-3Mh1Y8XdbbHJtXJLpvqLlu0pvkJOVib52IM", "email": "allen7575@gmail.com"}
```

It just a json file with 3 keys: url, doc_id, email, should be easy to implement, right? Or there are something I've missing...

**Comment by liberodark** [comment]
yes but need to add this fonctionnality is not implemented

**Comment by liberodark** [comment]
is dupicated
