### ISSUE TITLE
Not starting up automatically with the system startup.

### ISSUE THREAD

**Issue by srimaln91** [liberodark/ODrive#75]
The application does not start automatically with the system startup. I have already enabled the `Launch on startup` option.

OS : Ubuntu 18.04

**Comment by The-Graphite-Mog** [comment]
Hi,
same issue on Ubuntu 18.10.

**Comment by mtomlinson** [comment]
Yep, I have the exact same issue (18.10)

**Comment by srimaln91** [comment]
I would like to look into this issue.

**Comment by srimaln91** [comment]
Below are my system logs on the startup

```text
Mar 27 01:01:04 srimal-pc snap-userd-autostart.desktop[3247]: error: autostart failed for the following apps:
Mar 27 01:01:04 srimal-pc snap-userd-autostart.desktop[3247]: - "odrive-unofficial.desktop": cannot match desktop file with snap odrive-unofficial applications
Mar 27 01:01:04 srimal-pc gnome-shell[3010]: JS WARNING: [/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/appIcons.js 1028]: unreachable code after return statement
```

**Comment by liberodark** [comment]
You have test new version in official release ?

**Comment by liberodark** [comment]
**Please dont use odrive-unofficial !!!**

Use : that work on Ubuntu 18.04 have tested
https://github.com/liberodark/ODrive/releases/download/0.2.2/odrive_0.2.2_amd64.deb
