### ISSUE TITLE
Mint Crash / Icon Tray no visible

### ISSUE THREAD

**Issue by antrrax** [liberodark/ODrive#81]
Mint Cinnamon 19.1 x64

I install snap:
$ sudo snap install --edge odrive

Restart pc

I start OpenDrive
No icon is displayed on the tray, just an empty space
Or chrash icon: https://i.ibb.co/85TMbWr/icon.png

Note: Launch on startup dont work on Mint Cinnamon 19.1 x64

So I add the app manually at startup.
-start menu Mint
-system settings
-startup applications
-button add
-choose application
-type opendrive
-select opendrive app
-button add aplication

Restart pc
The icon is not displayed, but empty space appears on the tray.
Or chrash icon: https://i.ibb.co/85TMbWr/icon.png

******************
Note: If I close the session and log in again the Opendrive icon appears:
-start menu Mint
-logout icon
-button log out

-type password and login again

the icon appears
******************

my locale status:

$ locale

LANG=pt_BR.UTF-8
LANGUAGE=pt_BR
LC_CTYPE="pt_BR.UTF-8"
LC_NUMERIC=pt_BR.UTF-8
LC_TIME=pt_BR.UTF-8
LC_COLLATE="pt_BR.UTF-8"
LC_MONETARY=pt_BR.UTF-8
LC_MESSAGES="pt_BR.UTF-8"
LC_PAPER=pt_BR.UTF-8
LC_NAME=pt_BR.UTF-8
LC_ADDRESS=pt_BR.UTF-8
LC_TELEPHONE=pt_BR.UTF-8
LC_MEASUREMENT=pt_BR.UTF-8
LC_IDENTIFICATION=pt_BR.UTF-8
LC_ALL=

**Comment by liberodark** [comment]
Please try to use deb or appimage ?

**Comment by liberodark** [comment]
Have try is work https://i.imgur.com/CqAVFbg.png need deb
