### ISSUE TITLE
Critical bug when deleting folders locally

### ISSUE THREAD

**Issue by raphaelchinchilla** [liberodark/ODrive#86]
I observed the following critical bug when deleting a folder locally:

I deleted a folder locally by mistake. The folder contained some google docs files. When Odrive deletes a folder or a file on the server, it does not go to trash. Instead, it deletes the folder forever. 

The files that I had synched locally I was able to recover in my trash can. However, the google docs files I was only able to recover because I realized the problem very fast and contacted Google who recovered them for me.

I urge you to solve this issue. The google trash serves as a double buffer, and although it has many problems, it is better to have than to not.

**Comment by liberodark** [comment]
Need test for that

**Comment by raphaelchinchilla** [comment]
Would you like me to make the tests?

**Comment by raphaelchinchilla** [comment]
Hey, just wanted to check whether you are planning on fixing this issue. I personally consider it as a critical bug and have stopped using Odrive since then, which is a shame as Odrive is the best google drive sync for ubuntu out there.

**Comment by liberodark** [comment]
Fixed

**Comment by raphaelchinchilla** [comment]
thanks for correcting it! Is the snap package up to date or I should install from the git channel?
