### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by mmaryo** [liberodark/ODrive#89]
Hello 

With latest app for ubuntu 
I have this error juste after allow OpenDrive to connect to Google Drive
Then when I try again, it works

~ % /opt/odrive-0.1.3-x86_64.AppImage
installed: X-AppImage-BuildId=f83c5d80-3e33-11a8-3e38-f1e32563bb97 image: X-AppImage-BuildId=f83c5d80-3e33-11a8-3e38-f1e32563bb97
/tmp/.mount_odriveOmp453/app/resources/app.asar/public
app started on port 16409
Updating tray icon, connected:  true syncing:  false
Get home page
Number of accounts 0
GET / 200 19.380 ms - 755
GET /javascript/jquery.min.js 200 7.357 ms - 86659
GET /stylesheets/styles.css 200 4.834 ms - 173175
GET /settings 200 1.753 ms - 1695
GET /javascript/preload.js 200 2.422 ms - 274
GET /javascript/jquery.min.js 304 0.779 ms - -
GET /stylesheets/styles.css 304 0.247 ms - -
GET /javascript/tether.min.js 200 2.192 ms - 25045
GET /javascript/settings.js 200 3.100 ms - 1623
GET /javascript/frontend.js 200 3.650 ms - 196811
GET /files/af7ae505a9eed503f8b8e6982036873e.woff2 200 1.774 ms - 77160
Generating oauth url
GET /connect 302 4.375 ms - 628
Handling authentification code
GET /authCallback?code=4/MgFFZgrqu6EdOjLxsaI_h61dIpflXoc5r6g5o2amkoH1yvCT0GdkizrlUfRfkuLPanymJBm5adJlLdPuxKgoIS0&scope=https://www.googleapis.com/auth/drive 500 27959.467 ms - 594
Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1130:19)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at TLSSocket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by JincanDeng** [comment]
@mmaryo I meet the same error. Could I ask you how to solve it?

**Comment by liberodark** [comment]
Need proxy but need to see that later now have other fix for the 2.2

**Comment by liberodark** [comment]
same issue

**Comment by marcossv9** [comment]
Same issue here, what kind of proxy do you need? Can I help you @liberodark ? Sorry for comment on closed issue.
