### ISSUE TITLE
Cannot connect to Google Drive

### ISSUE THREAD

**Issue by richardchien** [liberodark/ODrive#96]
After I logged in my Google account, the following page took very long time.

![Screenshot_20190502_083117](https://user-images.githubusercontent.com/5317095/57051699-42f8e900-6cb5-11e9-9f4f-74fc4bf67371.png)

And then finally I got this:

![Screenshot_20190502_083412](https://user-images.githubusercontent.com/5317095/57051723-61f77b00-6cb5-11e9-8e17-8e17d87a6634.png)

And it's not connected. Any help?

**Comment by richardchien** [comment]
I'm using AUR `odrive-bin`

**Comment by richardchien** [comment]
I tried the AppImage version just now, and it behaved the same.

**Comment by liberodark** [comment]
Im on arch no have this problem ! please send more informations ?

**Comment by richardchien** [comment]
After some struggle, I finally get back to Windows😂, so…

**Comment by liberodark** [comment]
Ok
